// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoSmXY6hRwjSWN_pOC1Qe-UcbML_9_IV4',
    appId: '1:152698817266:web:2994f445d5e6528d555e6b',
    messagingSenderId: '152698817266',
    projectId: 'fitlife-fb7e9',
    authDomain: 'fitlife-fb7e9.firebaseapp.com',
    storageBucket: 'fitlife-fb7e9.firebasestorage.app',
    measurementId: 'G-Z0Q3KS6FB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo7ZzSFkI6_-WsSGV-FbmZ7tNMjN-YdQs',
    appId: '1:152698817266:android:43f86384554ff272555e6b',
    messagingSenderId: '152698817266',
    projectId: 'fitlife-fb7e9',
    storageBucket: 'fitlife-fb7e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj0Fs1nGXMGt4cLH_EfvQYJgriAYK5h18',
    appId: '1:152698817266:ios:4e68813f1a6df6f9555e6b',
    messagingSenderId: '152698817266',
    projectId: 'fitlife-fb7e9',
    storageBucket: 'fitlife-fb7e9.firebasestorage.app',
    iosBundleId: 'com.example.fitlifeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj0Fs1nGXMGt4cLH_EfvQYJgriAYK5h18',
    appId: '1:152698817266:ios:4e68813f1a6df6f9555e6b',
    messagingSenderId: '152698817266',
    projectId: 'fitlife-fb7e9',
    storageBucket: 'fitlife-fb7e9.firebasestorage.app',
    iosBundleId: 'com.example.fitlifeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoSmXY6hRwjSWN_pOC1Qe-UcbML_9_IV4',
    appId: '1:152698817266:web:c2f983fb3a966acc555e6b',
    messagingSenderId: '152698817266',
    projectId: 'fitlife-fb7e9',
    authDomain: 'fitlife-fb7e9.firebaseapp.com',
    storageBucket: 'fitlife-fb7e9.firebasestorage.app',
    measurementId: 'G-PD190XTNB1',
  );
}
